### ISSUE TITLE
If I want to get help, it's not clear where to go

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/website#21]
A lot of users come to the website because they need help with the tools. The current site has a clear HELP top-level menu item. Currently, it's not clear which top-level element to click on. 

Once I do get to the Software page, it's still not clear where I go from there.

My ideal top-level elements would be About / Community / Help / Download (it's still not clear to me how About and Software are differentiated). If not possible, perhaps adding Help in addition to the existing top-level elements would be ok?

As another possibility, adding Help to the Software left bar could also guide users.

**Comment by yanokwa** [comment]
This to me is a high priority issue that's related to #80. I think  `Community | Help | Download` is way clearer. 

Agreed that some of the stuff that is in About could really be put under Community.

**Comment by jbeorse** [comment]
I agree with this change. I think this new Help page should include a lot of what the "Software" page currently has, though possibly restructured. This includes:

- Links to the documentation, possibly to individual tools pages, and other common topics like form design or training guides (note that some of these links are currently broken on "Software"). 
- Link to the FAQ
- Link to the forum. This is duplicated on the Community page but I think its worth including in both, as it is the main avenue to ask questions. 
- Link to the Marketplace (should this be linked in Community too?)

We probably don't need the extensive description of each tool here. the way we did in Software. I think it might make more sense on a Help page to start with user stories or problems and then link to tools in the solutions.

**Comment by yanokwa** [comment]
I agree with links to docs, forum, and marketplace. Totally OK if there is some duplication from Community.

For docs, I think these should be high-level links not to individual tools. I say this because folks need context and dropping someone directly into the Aggregate getting started might not give them the right context. I also want to reduce the need to update links when we rename something on the docs side.

I'm a no on the FAQ. We've been moving away from them in the docs because it's hard to know what to put in there and hard to keep up-to-date. Another way to look at it is if there is an FAQ, then it means we haven't structured things properly to prevent questions from being asked frequently!

**Comment by yanokwa** [comment]
As far as the language, I'm thinking more that we say there are two primary ways to get help: the docs and the forum. 

Then we have links to ODK and ODK 2 docs. Then we have a link to the forum with sub-links to support, feature request, and marketplace categories. Then we have a contact email address for private issues. 

We will need to have some succinct language at the top that explains the differences between the two suites.

**Comment by wbrunette** [comment]
I agree that replacing the software page with a help page that links to resources is a good direction to head.
