### ISSUE TITLE
Entire "how we do it" section is a link

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/website#240]
Only the `Join the community` button should be a link.

**Comment by danbjoseph** [comment]
On the Minimal Mistake documentation
https://mmistakes.github.io/minimal-mistakes/docs/helpers/#feature-row

The last example in the section (Placeholder 2 with a Read More button) shows the same behavior.

Could remove the button for now? Since the "/community/" link is also at the end of the text paragraph.

**Comment by danbjoseph** [comment]
related: https://github.com/mmistakes/minimal-mistakes/pull/1864
